### ISSUE TITLE
貌似示意图都没很好的适配啊

### ISSUE THREAD

**Issue by limingLiuBaBa** [SunriseOYR/IBProperty#1]
![image](https://user-images.githubusercontent.com/22836046/40634787-6e05b362-6329-11e8-85a9-4284563731a9.png)
se 的框都显示不全了。。

**Comment by SunriseOYR** [comment]
这是模拟器渲染的原因(mac的问题)，因为我的手机就是se，截图的时候没发现,我过两天更新一哈截图
